### ISSUE TITLE
What is the motivation of this work?

### ISSUE THREAD

**Issue by mileswyn** [ziyangwang007/VMambaMorph#1]
No offense. 
This work is so similar to the MambaMorph, including the application task, the feature extractor, and the figure of method.
I wonder is it the only difference that the author changed the "Mamba" to "VMamba" in the registration framework?
If yes, it confuses me that what this work really contributes except just replacing a module from a pre-printed work.

**Comment by ziyangwang007** [comment]
Hi thanks for your message and your time.

I agree, the difference is somehow Mamba vs Visual Mamba. This is like Transformer vs Vision Transformer or TransUnet vs Swin Unet.


I understand the novelty is limited, and we decide to not submit this manuscript to anywhere for publication, just an extension report for mambamorph. Until we make some significant contribution, we then submit to a journal. As far as I know, mambamorph has been submitted to a conference.

( I have connected with the first author of mambamorph, and get his agreement. )

In the end, I completely agree with you, please just consider this manuscript as an extended report of mambamorph. Thanks again.

**Comment by pisgo** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
LightningK0ala, @brooklynrob, @hiepd, @Asuis, @cmcgov, @alansastre, @BlackSwanBay, @yang1fan2, @zlargon, @devinjdawson, @shriniwas26, @ywm007, @bangbanggo, @g1mv, @aidatorajiro, @pavelkrolov, @anrisovich, @FAKERINHEART, @siweilxy, @HarvestStars, @deeplink, @Juski, @dfshizhiqiang, @phuongnq, @matpratta, @Barbatos, @gtkesh, @hun-a, @brucedsu, @benmcp, @berkintosun, @zhouya2010, @baylesa-dev, @Joker208, @muhammad-hamdi, @kostiushkin, @bvolpato, @markrookie, @zhaojh329, @baillyjamy, @atkodev, @zhengying, @FancySpyder, @StevenZiu, @albrechta, @JoelBondurant, @Comodore125, @geheim01, @spb829, @Bartosz-D3V
